// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Symbolics.Com.Core.Infrastructure.Persistence;

#nullable disable

namespace Symbolics.Com.Core.Infrastructure.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20250320123000_AddLanguageToStreamer")]
    partial class AddLanguageToStreamer : Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Symbolics.Com.Core.Infrastructure.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("OptimizedDescription")
                        .HasColumnType("text");

                    b.Property<string>("UserDescription")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Campaign", (string)null);
                });

            modelBuilder.Entity("Symbolics.Com.Core.Infrastructure.Entities.ExternalServiceLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("CachedUnits")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExecutionTimeMs")
                        .HasColumnType("integer");

                    b.Property<long>("InputUnits")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("OutputUnits")
                        .HasColumnType("bigint");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Service", "ActionType");

                    b.ToTable("ExternalServiceLog", (string)null);
                });

            modelBuilder.Entity("Symbolics.Com.Core.Infrastructure.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsReady")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("VectorDescription")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_Game_IsReady")
                        .HasFilter("\"IsReady\" = TRUE");

                    b.ToTable("Game", (string)null);
                });

            modelBuilder.Entity("Symbolics.Com.Core.Infrastructure.Entities.GameEnrichmentQueue", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("GameId");

                    b.ToTable("GameEnrichmentQueue", (string)null);
                });

            modelBuilder.Entity("Symbolics.Com.Core.Infrastructure.Entities.GamePlayed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StreamerId")
                        .HasColumnType("uuid");

                    b.Property<string>("TwitchStreamId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ViewerCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("GameId");

                    b.HasIndex("TwitchStreamId")
                        .IsUnique();

                    b.HasIndex("StreamerId", "GameId", "Date")
                        .IsUnique();

                    b.ToTable("GamePlayed", (string)null);
                });

            modelBuilder.Entity("Symbolics.Com.Core.Infrastructure.Entities.GameTwitch", b =>
                {
                    b.Property<string>("TwitchId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("TwitchName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("TwitchId");

                    b.HasIndex("GameId");

                    b.ToTable("GameTwitch", (string)null);
                });

            modelBuilder.Entity("Symbolics.Com.Core.Infrastructure.Entities.Streamer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Language")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsReady")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PersonaDescription")
                        .HasColumnType("text");

                    b.Property<string>("VectorDescription")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_Streamer_IsReady")
                        .HasFilter("\"IsReady\" = TRUE");

                    b.ToTable("Streamer", (string)null);
                });

            modelBuilder.Entity("Symbolics.Com.Core.Infrastructure.Entities.StreamerEnrichmentQueue", b =>
                {
                    b.Property<Guid>("StreamerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("StreamerId");

                    b.ToTable("StreamerEnrichmentQueue", (string)null);
                });

            modelBuilder.Entity("Symbolics.Com.Core.Infrastructure.Entities.StreamerTwitch", b =>
                {
                    b.Property<string>("TwitchId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("StreamerId")
                        .HasColumnType("uuid");

                    b.Property<string>("TwitchLogin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TwitchName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("TwitchId");

                    b.HasIndex("StreamerId");

                    b.ToTable("StreamerTwitch", (string)null);
                });

            modelBuilder.Entity("Symbolics.Com.Core.Infrastructure.Entities.StreamerYoutube", b =>
                {
                    b.Property<Guid>("StreamerId")
                        .HasColumnType("uuid");

                    b.Property<string>("YoutubeUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("StreamerId");

                    b.ToTable("StreamerYoutube", (string)null);
                });

            modelBuilder.Entity("Symbolics.Com.Core.Infrastructure.Entities.WorkerState", b =>
                {
                    b.Property<string>("WorkerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CurrentCursor")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastCleanupDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WorkerName");

                    b.ToTable("WorkerState", (string)null);
                });

            modelBuilder.Entity("Symbolics.Com.Core.Infrastructure.Entities.GameEnrichmentQueue", b =>
                {
                    b.HasOne("Symbolics.Com.Core.Infrastructure.Entities.Game", "Game")
                        .WithOne("EnrichmentQueue")
                        .HasForeignKey("Symbolics.Com.Core.Infrastructure.Entities.GameEnrichmentQueue", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Symbolics.Com.Core.Infrastructure.Entities.GamePlayed", b =>
                {
                    b.HasOne("Symbolics.Com.Core.Infrastructure.Entities.Game", "Game")
                        .WithMany("PlayedEntries")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Symbolics.Com.Core.Infrastructure.Entities.Streamer", "Streamer")
                        .WithMany("PlayedEntries")
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("Symbolics.Com.Core.Infrastructure.Entities.GameTwitch", b =>
                {
                    b.HasOne("Symbolics.Com.Core.Infrastructure.Entities.Game", "Game")
                        .WithMany("TwitchMappings")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Symbolics.Com.Core.Infrastructure.Entities.StreamerEnrichmentQueue", b =>
                {
                    b.HasOne("Symbolics.Com.Core.Infrastructure.Entities.Streamer", "Streamer")
                        .WithOne("EnrichmentQueue")
                        .HasForeignKey("Symbolics.Com.Core.Infrastructure.Entities.StreamerEnrichmentQueue", "StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("Symbolics.Com.Core.Infrastructure.Entities.StreamerTwitch", b =>
                {
                    b.HasOne("Symbolics.Com.Core.Infrastructure.Entities.Streamer", "Streamer")
                        .WithMany("TwitchMappings")
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("Symbolics.Com.Core.Infrastructure.Entities.StreamerYoutube", b =>
                {
                    b.HasOne("Symbolics.Com.Core.Infrastructure.Entities.Streamer", "Streamer")
                        .WithOne("Youtube")
                        .HasForeignKey("Symbolics.Com.Core.Infrastructure.Entities.StreamerYoutube", "StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("Symbolics.Com.Core.Infrastructure.Entities.Game", b =>
                {
                    b.Navigation("EnrichmentQueue");

                    b.Navigation("PlayedEntries");

                    b.Navigation("TwitchMappings");
                });

            modelBuilder.Entity("Symbolics.Com.Core.Infrastructure.Entities.Streamer", b =>
                {
                    b.Navigation("EnrichmentQueue");

                    b.Navigation("PlayedEntries");

                    b.Navigation("TwitchMappings");

                    b.Navigation("Youtube");
                });
#pragma warning restore 612, 618
        }
    }
}
